<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.phonepe.sentinel-ai</groupId>
    <artifactId>sentinel-ai</artifactId>
    <version>1.1.1-alpha4-1</version>
    <name>Sentinel AI</name>
    <url>https://github.com/PhonePe/sentinel-ai</url>
    <description>Sentinel AI Agent Framework</description>
    <inceptionYear>2025</inceptionYear>
    <scm>
        <connection>scm:git:https://github.com/PhonePe/sentinel-ai.git</connection>
        <developerConnection>scm:git:https://github.com/PhonePe/sentinel-ai.git</developerConnection>
        <tag>HEAD</tag>
        <url>https://github.com/PhonePe/sentinel-ai</url>
    </scm>

    <issueManagement>
        <system>GitHub Issues</system>
        <url>https://github.com/PhonePe/sentinel-ai/issues</url>
    </issueManagement>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>santanusinha</id>
            <name>Santanu Sinha</name>
            <email>santanu.sinha@gmail.com</email>
        </developer>
        <developer>
            <id>praveen97uma</id>
            <name>Praveen Kumar</name>
            <email>praveen.k@phonepe.com</email>
        </developer>
        <developer>
            <id>shubham-sharma-12</id>
            <name>Shubham Sharma</name>
            <email>shubham.sha12@gmail.com</email>
        </developer>
        <developer>
            <id>avanishp</id>
            <name>Avanish Pandey</name>
            <email>avanish.pandey1@phonepe.com</email>
        </developer>
        <developer>
            <id>kanikakhetawat</id>
            <name>Kanika Khetawat</name>
            <email>kanikakhetawat.kk@gmail.com</email>
        </developer>
        <developer>
            <id>ektamishra</id>
            <name>Ekta Mishra</name>
            <email>ektamishra1999@gmail.com</email>
        </developer>
    </developers>

    <packaging>pom</packaging>

    <modules>
        <module>sentinel-ai-core</module>

        <!-- models -->
        <module>sentinel-ai-models-simple-openai</module>
        <module>sentinel-ai-embedding</module>

        <!-- toolboxes -->
        <module>sentinel-ai-toolbox-mcp</module>
        <module>sentinel-ai-toolbox-remote-http</module>

        <!-- extensions -->
        <module>sentinel-ai-agent-memory</module>
        <module>sentinel-ai-session</module>
        <module>sentinel-ai-filesystem</module>
        <module>sentinel-ai-configured-agents</module>

        <!-- Storage implementations -->
        <module>sentinel-ai-storage-es</module>

        <!-- All other modules above this -->
        <module>sentinel-ai-bom</module>
        <module>sentinel-ai-reporting</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <lombok.version>1.18.38</lombok.version>
        <slf4j-api.version>2.0.17</slf4j-api.version>
        <signals.version>1.4</signals.version>
        <awaitility.version>4.2.0</awaitility.version>
        <guice.version>6.0.0</guice.version>
        <logback.version>1.5.18</logback.version>
        <failsafe.version>3.3.2</failsafe.version>
        <junit.version>5.8.2</junit.version>
        <wiremock.version>3.3.1</wiremock.version>
        <maven.deploy.skip>false</maven.deploy.skip>
        <commons-validator.version>1.4.1</commons-validator.version>
        <guava.version>32.1.3-jre</guava.version>
        <okhttp.version>4.12.0</okhttp.version>
        <sonar.organization>phonepe</sonar.organization>
        <sonar.host.url>https://sonarcloud.io</sonar.host.url>
        <sonar.java.coveragePlugin>jacoco</sonar.java.coveragePlugin>
        <sonar.dynamicAnalysis>reuseReports</sonar.dynamicAnalysis>
        <sonar.language>java</sonar.language>
        <sonar.qualitygate.wait>true</sonar.qualitygate.wait>
        <sonar.coverage.jacoco.xmlReportPaths>${project.basedir}/../sentinel-ai-reporting/target/site/jacoco-aggregate/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
        <maven-javadoc-plugin.version>3.8.0</maven-javadoc-plugin.version>
        <maven-source-plugin.version>3.3.0</maven-source-plugin.version>
        <commons-text.version>1.13.1</commons-text.version>
        <jackson.version>2.18.3</jackson.version>
        <mockito.version>5.20.0</mockito.version>
        <testcontainers.version>1.21.4</testcontainers.version>
        <spotless.version>3.2.1</spotless.version>
        <sentinelai.useRealEndpoints>false</sentinelai.useRealEndpoints>
        <dotenv.file>${sentinelai.root}/sentinel-ai-core/src/test/resources/test.env</dotenv.file>
        <console.disable>true</console.disable>
        <success.print>false</success.print>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.fasterxml.jackson</groupId>
                <artifactId>jackson-bom</artifactId>
                <version>${jackson.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-validator</groupId>
                <artifactId>commons-validator</artifactId>
                <version>${commons-validator.version}</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>${okhttp.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.awaitility</groupId>
            <artifactId>awaitility</artifactId>
            <version>${awaitility.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.wiremock</groupId>
            <artifactId>wiremock-standalone</artifactId>
            <version>${wiremock.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.commonjava.maven.plugins</groupId>
                <artifactId>directory-maven-plugin</artifactId>
                <version>1.0</version>
                <executions>
                    <execution>
                        <id>directories</id>
                        <goals>
                            <goal>highest-basedir</goal>
                        </goals>
                        <phase>initialize</phase>
                        <configuration>
                            <property>sentinelai.root</property>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                    <compilerArgument>-parameters</compilerArgument>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok-maven-plugin</artifactId>
                <version>1.18.20.0</version>
                <dependencies>
                    <dependency>
                        <groupId>org.projectlombok</groupId>
                        <artifactId>lombok</artifactId>
                        <version>${lombok.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <sourceDirectory>${project.basedir}/src/main/java</sourceDirectory>
                    <outputDirectory>${delombok.output}</outputDirectory>
                    <addOutputDirectory>false</addOutputDirectory>
                </configuration>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>delombok</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>${maven-javadoc-plugin.version}</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <source>17</source>
                    <sourcepath>target/generated-sources/delombok/</sourcepath>
                    <doclint>none</doclint>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>${maven-source-plugin.version}</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.3.1</version>
                <dependencies>
                    <dependency>
                        <groupId>me.fabriciorby</groupId>
                        <artifactId>maven-surefire-junit5-tree-reporter</artifactId>
                        <version>1.3.0</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <reportFormat>plain</reportFormat>
                    <consoleOutputReporter>
                        <disable>${console.disable}</disable>
                    </consoleOutputReporter>
                    <statelessTestsetInfoReporter
                            implementation="org.apache.maven.plugin.surefire.extensions.junit5.JUnit5StatelessTestsetInfoTreeReporter">
                        <printStacktraceOnError>true</printStacktraceOnError>
                        <printStacktraceOnFailure>true</printStacktraceOnFailure>
                        <printStdoutOnError>true</printStdoutOnError>
                        <printStdoutOnFailure>true</printStdoutOnFailure>
                        <printStdoutOnSuccess>${success.print}</printStdoutOnSuccess>
                        <printStderrOnError>true</printStderrOnError>
                        <printStderrOnFailure>true</printStderrOnFailure>
                        <printStderrOnSuccess>${success.print}</printStderrOnSuccess>
                    </statelessTestsetInfoReporter>
                    <systemPropertyVariables>
                        <sentinelai.useRealEndpoints>${sentinelai.useRealEndpoints}</sentinelai.useRealEndpoints>
                        <dotenv.file>${dotenv.file}</dotenv.file>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.14</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>${spotless.version}</version>
                <configuration>
                    <java>
                        <licenseHeader>
                            <file>${maven.multiModuleProjectDirectory}/license.header</file>
                        </licenseHeader>
                        <eclipse>
                            <version>4.38</version>
                            <file>${maven.multiModuleProjectDirectory}/java-format.xml</file>
                            <sortMembersEnabled>true</sortMembersEnabled>
                            <!-- Sort order
                            - Static Fields
                            - Type Definitions
                            - Initializers
                            - Field Definitions
                            - Field Initializers
                            - Constructor
                            - Static functions
                            - Methods
                            -->
                            <sortMembersOrder>SF,T,SI,F,I,C,SM,M</sortMembersOrder>
                            <sortMembersVisibilityOrderEnabled>true</sortMembersVisibilityOrderEnabled>
                            <!--
                            - Public
                            - Protected
                            - Package
                            - Private
                            -->
                            <sortMembersVisibilityOrder>B,R,D,V</sortMembersVisibilityOrder>
                        </eclipse>
                        <removeUnusedImports/>
                        <importOrder>
                        <order>com,io,org,com.phonepe,,java,javax,\#</order>
                        <semanticSort>true</semanticSort>
                        </importOrder>
                        <trimTrailingWhitespace/>
                        <forbidWildcardImports/>
                        <endWithNewline/>
                        <!-- <ratchetFrom>origin/master</ratchetFrom> -->
                    </java>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <phase>compile</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>central-release</id>
            <activation>
                <property>
                    <name>release</name>
                    <value>true</value>
                </property>
            </activation>
            <distributionManagement>
                <snapshotRepository>
                    <id>ossrh</id>
                    <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
                </snapshotRepository>
                <repository>
                    <id>ossrh</id>
                    <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
                </repository>
            </distributionManagement>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>0.5.0</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>github</publishingServerId>
                            <autoPublish>true</autoPublish>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>1.6</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                                <configuration>
                                    <gpgArguments>
                                        <arg>--pinentry-mode</arg>
                                        <arg>loopback</arg>
                                    </gpgArguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>real-tests</id>
            <properties>
                <dotenv.file>${sentinelai.root}/.env</dotenv.file>
                <console.disable>false</console.disable>
                <success.print>true</success.print>
                <sentinelai.useRealEndpoints>true</sentinelai.useRealEndpoints>
            </properties>
        </profile>
    </profiles>
</project>
